---
- name: Configure Amazon Linux
  hosts: frontend
  become: true

  tasks:

    - name: Set hostname
      ansible.builtin.hostname:
        name: c8.local

    - name: Install Apache
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Start and enable Apache
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Create test page
      ansible.builtin.copy:
        content: |
          <html>
          <body>
          <h1>Hello from Amazon Linux - c8.local</h1>
          </body>
          </html>
        dest: /var/www/html/index.html
        mode: '0644'
